services:
  postgres:
    image: postgres
    container_name: osint_db
    restart: always
    environment:
      POSTGRES_DB: osint_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: osint_backend
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/osint_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build:
      context: ../../../Projects/PTBOX-osint-FE/ptbox-osint-fe/
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
#    environment:
#      REACT_APP_BACKEND_URL: http://backend:8080

volumes:
  postgres_data:
